/** Agent 页面 UI 文案（集中管理，避免编码损坏） */

export const AGENT_UI = {
  sidebarSub: '教师问答助手',
  newChat: '新建对话',
  sessionCount: (n) => `共 ${n} 个会话`,

  searchSessions: '搜索会话…',
  sessionsLoading: '加载中…',
  noSessions: '暂无会话',
  noSessionMatch: '无匹配会话',
  defaultSessionTitle: '新对话',
  renameSession: '重命名会话',
  cancel: '取消',
  save: '保存',
  deleteConfirm: (title) => `确定删除「${title}」？`,

  emptyTitle: '开始新的分析',
  emptyDesc: '基于班级数据提问，或使用 /skill 加载分析流程技能。',
  emptySkillList: '/skill 列出技能',

  composerPlaceholder: '输入问题；/skill 列出技能，/skill analysis-class 加载技能',
  composerHint: 'Enter 发送 · Shift+Enter 换行 · /skill · /memories',
  skillSlashListing: '列出技能',
  skillSlashLoading: (name) => `加载技能 ${name}`,
  send: '发送',
  stop: '停止',
  stoppedHint: '已停止生成',

  backDashboard: '返回可视化',
  toggleSidebar: '切换会话栏',
  toggleRail: '切换信息栏',
  defaultTitle: '新对话',
  clickToEditTitle: '点击编辑',
  floatMode: '浮窗',

  railScope: '分析范围',
  railScopeShort: '范围',
  railClass: '班级',
  railMajor: '专业',
  railStudents: '选中学生',
  railStudentsCount: (n) => `${n} 人`,
  railNoScope: '未限定范围，将基于全局数据回答',
  railAdjustScope: '在可视化中调整范围 →',
  railScopeLoading: '正在加载筛选…',
  railApplyScope: '应用筛选',
  railApplying: '应用中…',
  railOpenViz: '打开可视化查看',
  railScatter: '学生簇分布',
  railScatterLoading: '正在刷新散点…',
  railBrush: '框选',
  railClick: '点选',
  railWeekRange: '周次范围',
  railWeekLocked: '调整周次',
  railWeekUnlock: '锁定周次',
  railSelectedStudents: (n) => `已选 ${n} 名学生`,
  railScopeHint: '班级/专业/周次与散点选择会作为 Agent 分析范围',
  railMode: '能力模式',
  modeConsult: '咨询 — 只读建议',
  modeAnalyze: '分析 — 查询统计',
  modeProduce: '产出 — 可写文件',
  railPlan: '执行计划',
  railSkills: '已加载技能',
  todoStepTitle: '更新计划',
  todoStepDone: '已完成',
  todoAcceptance: '验收',
  skillStepTitle: '加载技能',
  memorySection: '已记住',
  memoryRail: '持久记忆',
  memoryRailShortHint: '以下为会注入每次分析的长期约定（具名记忆）。',
  memoryRailManage: '管理',
  memoryRailRollingSection: '滚动笔记',
  memoryRailRollingHint:
    'Agent 通过 memory 工具追加的流水账（user_profile / agent_notes）。任务状态不应出现在这里，请定期清理。',
  memoryRailNamedSection: '我的约定',
  memoryRailNamedHint: '具名跨会话记忆，可新建、启用/停用。',
  memoryRailActiveEmpty: '暂无已启用记忆。点「管理」新建或启用。',
  memoryRailDisabledCount: (n) => `另有 ${n} 条已停用（在管理窗口中可重新启用）`,
  memoryModalTitle: '记忆管理',
  memoryEnabled: '注入 Agent',
  memoryEnabledHint:
    '勾选后会在后续 analyze/produce 的 system prompt 中生效。取消勾选只影响之后的新消息，不会改写当前会话里已经发生的对话。',
  memoryRailIntro:
    '保存「以后每次对话都要遵守的约定」。可新建、编辑、启用/停用；分析结论请写入报告文件，不要贴在这里。',
  memoryRailEmpty: '还没有任何记忆。点「新建」添加。',
  memoryRailRefresh: '刷新',
  memoryRailNew: '新建',
  memoryEdit: '编辑',
  memoryFieldName: '标识',
  memoryHintName:
    '给这条记忆起一个短名字（英文、数字、下划线），方便区分，例如 class1_报告版式。仅新建时可填，创建后不能改名。',
  memoryNamePlaceholder: '例如 class1_report_style',
  memoryFieldType: '类别',
  memoryHintType: '告诉 Agent 这条信息属于哪一类，便于归类理解。',
  memoryTypeUser: '教师偏好',
  memoryTypeUserDesc: '您的习惯：默认班级、报告用表格还是段落、常用关注点等。',
  memoryTypeFeedback: '分析纠正',
  memoryTypeFeedbackDesc: '您曾指出 Agent 分析不对、希望以后换种写法或方法。',
  memoryTypeProject: '项目约定',
  memoryTypeProjectDesc: '本系统/本班特有的规则（catalog 里写不清的）。',
  memoryTypeReference: '外部参考',
  memoryTypeReferenceDesc: '文档链接、制度说明等（不要存整张数据表）。',
  memoryFieldDescription: '一句话摘要',
  memoryHintDescription: '在列表里显示，帮您快速认出这条记忆，不必写很长。',
  memoryDescriptionPlaceholder: '例如：Class1 报告优先用表格',
  memoryFieldContent: '要记住的内容',
  memoryHintContent:
    'Agent 今后会按这里写的来回答、写报告。写清楚即可，宜短不宜长；统计数字和字段说明请放在报告文件里，不要贴在这里。',
  memoryContentPlaceholder: '例如：Class1 学情报告结论放表下，图表用折线不用饼图。',
  memoryCreate: '创建',
  memoryRailOpen: '管理',
  memoryDeleteConfirm: (name) => `删除记忆「${name}」？`,
  memoryEditTitle: (name) => `编辑：${name}`,
  memoryNameReadonly: '标识（不可修改）',
  memorySave: '保存修改',
  memoryLoading: '加载中…',
  memorySavedChip: (label) => `已记住：${label}`,
  memoryListHint: '具名记忆（停用项为灰色）；滚动笔记见下方。',

  reportSection: '报告与导出',
  reportPreview: '预览',
  reportExport: '导出',
  reportExportMd: '下载 Markdown',
  reportExportHtml: '导出 HTML（含图表）',
  reportExporting: '正在导出…',
  reportPreviewTitle: '报告预览',
  reportLoading: '正在加载报告…',
  reportEmpty: '暂无内容',
  railMeta: '会话信息',
  railMessageCount: '消息数',

  permissionTitle: '需要权限确认',
  deny: '拒绝',
  allowOnce: '允许一次',
  allowAlways: '永久允许',

  rename: '重命名',
  delete: '删除',
  messageUnit: '条',
  /** 会话列表副标题：消息条数 + Agent 用户轮次（与 loop turn 一致） */
  sessionListMeta: (messageCount, turnCount) =>
    `消息 ${messageCount} | 轮次 ${turnCount}`,

  toolParams: '参数',
  toolError: '错误',
  toolStatusOk: '成功',
  toolStatusFail: '失败',
  toolStatusDenied: '拒绝',
  toolStatusBlocked: '拦截',
  toolStatusRunning: '执行中',

  sectionPlan: '分析计划',
  sectionProcess: '执行过程',
  sectionConclusion: '分析结论',

  sampleQuestions: [
    '最近两周链表知识点表现如何？',
    '哪些学生需要重点关注？',
    '班级整体作业提交率趋势怎样？',
  ],
}
